enum WSDiscordEvent {
    READY = "READY",
    QUIT = "RESUMED",
    RECONNECT = "RECONNECT",
    MESSAGE_REACTION_ADD = "MESSAGE_REACTION_ADD",
    MESSAGE_REACTION_REMOVE = "MESSAGE_REACTION_REMOVE",
    CHANNEL_CREATE = "CHANNEL_CREATE",
    CHANNEL_DELETE = "CHANNEL_DELETE",
    CHANNEL_UPDATE = "CHANNEL_UPDATE",
    MESSAGE_CREATE = "MESSAGE_CREATE",
    MESSAGE_DELETE = "MESSAGE_DELETE",
    MESSAGE_UPDATE = "MESSAGE_UPDATE",
}
