export enum WSBotErrorEvent {
    COMMANDE_EXECUTE = "COMMANDE_EXECUTE",
    BAD_ARGS_NUMBER = "BAD_ARGS_NUMBER",
    BAD_ARGS_TYPE = "BAD_ARGS_TYPE",
    NOT_ENOUGHT_PERMISSION = "NOT_ENOUGHT_PERMISSION",
    CANNOT_LOAD_SONG = "CANNOT_LOAD_SONG",
    UNKNOWN_COMMANDE = "UNKNOWN_COMANDE",
    EMIT_ERROR = "EMIT_ERROR",

    UNKNOWN_ERROR = "UNKNOWN_ERROR"
}

export enum WSBotChannelErrorEvent {
    CHANNEL_UPDATE = "CHANNEL_UPDATE",
    CHANNEL_CREATION = "CHANNEL_CREATION",
    CHANNEL_LINKING = "CHANNEL_LINKING",
    CHANNEL_UNLINK = "CHANNEL_UNLINK",
    CHANNEL_UNKNOWN_COMMANDE = "CHANNEL_UNKNOWN_COMMANDE",

    CHANNEL_UNKNOWN_ERROR = "CHANNEL_UNNOWN_ERROR"
}