export enum WSBotErrorEvent {
    COMMANDE_EXECUTE = "COMMANDE_EXECUTE",
    BAD_ARGS_NUMBER = "BAD_ARGS_NUMBER",
    BAD_ARGS_TYPE = "BAD_ARGS_TYPE",
    NOT_ENOUGHT_PERMISSION = "NOT_ENOUGHT_PERMISSION",
    CANNOT_LOAD_SONG = "CANNOT_LOAD_SONG",
    UNKNOWN_COMMANDE = "UNKNOWN_COMANDE",
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
}